spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${PC_CONFIG_APP_DB_HOST}:${PC_CONFIG_APP_DB_PORT}/${PC_CONFIG_APP_DB_NAME}
    generate-unique-name: false
    name: ${PC_CONFIG_APP_DB_NAME}
    username: ${PC_CONFIG_APP_DB_USERNAME}
    password: ${PC_CONFIG_APP_DB_PASSWORD}

  docker:
    compose:
      enabled: false # fixme enable for using docker compose
      file: docker-compose.yml

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  liquibase:
    change-log: classpath:db/changelog/changelog-master.yml