INSERT INTO vendor(id, name)
VALUES (GEN_RANDOM_UUID(), 'ASUS'),
       (GEN_RANDOM_UUID(), 'Asrock'),
       (GEN_RANDOM_UUID(), 'ColorFul'),
       (GEN_RANDOM_UUID(), 'GIGABYTE'),
       (GEN_RANDOM_UUID(), 'Inno3D'),
       (GEN_RANDOM_UUID(), 'KFA2'),
       (GEN_RANDOM_UUID(), 'MSI'),
       (GEN_RANDOM_UUID(), 'Palit'),
       (GEN_RANDOM_UUID(), 'Sapphire'),
       (GEN_RANDOM_UUID(), 'Zotac'),
       (GEN_RANDOM_UUID(), 'EVGA'),
       (GEN_RANDOM_UUID(), 'Biostar'),
       (GEN_RANDOM_UUID(), 'MaxSun'),
       (GEN_RANDOM_UUID(), 'ADATA'),
       (GEN_RANDOM_UUID(), 'Apacer'),
       (GEN_RANDOM_UUID(), 'Corsair'),
       (GEN_RANDOM_UUID(), 'Crucial'),
       (GEN_RANDOM_UUID(), 'G.Skill'),
       (GEN_RANDOM_UUID(), 'Goodram'),
       (GEN_RANDOM_UUID(), 'Dell'),
       (GEN_RANDOM_UUID(), 'HP'),
       (GEN_RANDOM_UUID(), 'Kingston'),
       (GEN_RANDOM_UUID(), 'Netac'),
       (GEN_RANDOM_UUID(), 'Patriot'),
       (GEN_RANDOM_UUID(), 'XPG'),
       (GEN_RANDOM_UUID(), 'Thermaltake'),
       (GEN_RANDOM_UUID(), 'AeroCool'),
       (GEN_RANDOM_UUID(), 'AORUS'),
       (GEN_RANDOM_UUID(), 'be quiet!'),
       (GEN_RANDOM_UUID(), 'Chieftec'),
       (GEN_RANDOM_UUID(), 'CoolerMaster'),
       (GEN_RANDOM_UUID(), 'Cougar'),
       (GEN_RANDOM_UUID(), 'DEEPCOOL'),
       (GEN_RANDOM_UUID(), 'Fractal Design'),
       (GEN_RANDOM_UUID(), 'FSP'),
       (GEN_RANDOM_UUID(), 'Montech'),
       (GEN_RANDOM_UUID(), 'Super Flower'),
       (GEN_RANDOM_UUID(), 'SilverStone'),
       (GEN_RANDOM_UUID(), 'ZALMAN'),
       (GEN_RANDOM_UUID(), 'ID-Cooling'),
       (GEN_RANDOM_UUID(), 'Arctic Cooling'),
       (GEN_RANDOM_UUID(), 'Noctua'),
       (GEN_RANDOM_UUID(), 'Western Digital');